### PR TITLE
Add Score Board in the Tic-Tac-Toe Game

### PR DESCRIPTION
**Pull request by pulkitgxrg**
Hi @arujjval, I have added score board in the tic-tac-toe game as per issue #13 assigned to me.

### CODE REVIEW

**Comment by arujjval** [comment]
Your PR is causing conflicts. Try making a separate function to implement this rather than adding it to the existing function.

**Comment by arujjval** [comment]
Also, mention the issue you are resolving.

**Comment by pulkitgxrg** [comment]
> Also, mention the issue you are resolving.

@arujjval, I am solving the issue #13 as per assigned to me. I have also resolved conflicts.

**Comment by arujjval** [comment]
Thanks for your contribution.

**Comment by arujjval** [comment]
Your PR has caused a deployment issue. I am reverting these changes.

**Comment by pulkitgarg04** [comment]
> Your PR has caused a deployment issue. I am reverting these changes.

I am not sure what has happened. Is this because of the changes I made? It was all working on my end.

**Pull request merged**
