### PR TITLE
Added website link in Readme.md

### LINKED ISSUE #9: Add website link in README.md
Add the website link in README.md. You can check other repos to figure out where to mention it in the file.

### PR DESCRIPTION
**Pull request by kshitijhadke26**
This PR adds a website link in Readme.md file.

Fixes #9 

image

### CODE REVIEW

**Comment by arujjval** [comment]
I think you should add this in the top part, along with the project's intro.

**Comment by kshitijhadke26** [comment]
Ok I will do that

**Comment by kshitijhadke26** [comment]
> I think you should add this in the top part, along with the project's intro.

I had added website link to top of the readme along with projects intro. please checked it out. Thank you.

Fixes #9 and #17 

image

**Comment by arujjval** [comment]
LGTM!

**Pull request merged**
